package com.SpringPractice.store;

import com.SpringPractice.store.entities.Address;
import com.SpringPractice.store.entities.Profile;
import com.SpringPractice.store.entities.Tag;
import com.SpringPractice.store.entities.User;
import com.SpringPractice.store.repositories.UserRepository;
import com.SpringPractice.store.services.UserService;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ApplicationContext;

@SpringBootApplication
public class StoreApplication {

	public static void main(String[] args) {
		//example of using constructor to initialize all fields
		//var user = new User(1L, "name", "email", "password");

		//example of using getters and setters
		//var user2 = new User();
		//user2.setName("John");
		//user2.setEmail("john@example.com");
		//user2.setPassword("password");

		//example of using builder
		//helps to create complex obj step by step especially if there are lots of optional fields of config
		/*var user = User.builder()
				.name("John")
				.password("1234")
				.email("john@example.com")
				.build();
		*/
		/*
		var address = Address.builder()
				.street("street")
				.city("city")
				.state("state")
				.zip("zip")
				.build();
		*/
		//Address one to many example/////////////////////////////////////////////////////////////
		// Update the inverse side (the collection on User)
		// This does NOT affect the database, but keeps the in-memory object graph consistent
		//user.getAddresses().add(address);//user now knows about the addresses

		// Set the owning side of the relationship
		// This is the ONLY side that updates the database (sets address.user_id)
		//address.setUser(user); //address now knows about user
		//these 2 relations are highly related and required to run so it's best to put logic inside user class/////

		//replaces the 2 above lines with helper method inside User class
		//user.addAddress(address);

		//System.out.println(user);

		//Tag many to many example////////////////////////////////////////////////////////////////
		//var tag = new Tag("tag1");

		//wiring tag and user objects together, same as above
		//put below 2 in helper method user class
		//user.getTags().add(tag);
		//tag.getUsers().add(user);

		//user.addTag("tag1");//replaces the lines above

		//System.out.println(user);

		//Profile one to one example////////////////////////////////////////////////////////////////
		//var profile = Profile.builder()
		//				.bio("bio")
		//				.build();
		//user.setProfile(profile);
		//profile.setUser(user);

		//System.out.println(user);


		ApplicationContext context = SpringApplication.run(StoreApplication.class, args);
		//create a repository object
		//the class/implementation of UserRepository interface is generated by spring at runtime
		//var repository = context.getBean(UserRepository.class);
		//var user = User.builder()
		//		.name("John")
		//		.email("john@gmail.com")
		//		.password("password")
		//		.build();
		//save in db (using repositories allows us to let hibernate do the SQL)
		//repository.save(user);//hibernate will take care of generating SQL statements at runtime

		//retrieve a user from db by id
		//var user = repository.findById(1L)/*.orElse(null)*/.orElseThrow(); //we can return null or error if no user
		//System.out.println(user.getEmail());

		//both of these 2 transactions are separate (2 persistence context) but cant apply @Transactional to static methods
		//retrieve all users from db (find all ret iterable so we can use a for each loop)
		//repository.findAll().forEach(u -> System.out.println(u.getEmail())); //for each user u, print user email
		//delete a user from db by id
		//repository.deleteById(1L); //(hibernate deletes child records from associated tables first before the user)

		//create userService to demonstrate @Transactional
		var service = context.getBean(UserService.class);
		//service.showEntityStates();

		//demonstrating lazy loading
		service.showRelatedEntities();
		service.showRelatedEntities2();
		//example 2 lazy loading
		service.fetchAddress();
	}

}
