package com.codewithmosh.store.entities;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.LinkedHashSet;
import java.util.Set;
import java.util.UUID;

//create entities if db tables exists using jpa buddy (rmb entities, new, JPA entities from db, select tables, check references, generate)
@Getter
@Setter
@Entity
@Table(name = "carts")
public class Cart { //removed unnecessary annotations and constraints to simplify the code (check CartItem for why)
    @Id
    @GeneratedValue(strategy = GenerationType.UUID) //instead of identity we set to uuid
    @Column(name = "id")
    private UUID id;
    //this field is also generated by the db we cannot apply generatedValue because it's only used for primary fields (@Id)
    @Column(name = "date_created", insertable = false, updatable = false) //tell hibernate to ignore this field when generating SQL statements
    private LocalDate dateCreated;

    //when we save a parent object (cart), the children are not saved (cartItems)
    @OneToMany(mappedBy = "cart", cascade = CascadeType.MERGE) //to fix use merge for updating because this is an existing cart
    private Set<CartItem> items = new LinkedHashSet<>();//rename cartItems to items so mapper can auto map to dto field

    //calculation is a part of domain logic, so we have to implement it in the entity
    public BigDecimal getTotalPrice() { //doesn't match any name in our dto, we need custom mapping in cart mapper
        return items.stream()
                .map(CartItem::getTotalPrice)
                .reduce(BigDecimal.ZERO, BigDecimal::add); //[10, 20, 30], then reduce to a single number starting with 0 and add each number
    }
}