package com.codewithmosh.store.entities;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.time.LocalDate;
import java.util.LinkedHashSet;
import java.util.Set;
import java.util.UUID;

//create entities if db tables exists using jpa buddy (rmb entities, new, JPA entities from db, select tables, check references, generate)
@Getter
@Setter
@Entity
@Table(name = "carts")
public class Cart { //removed unnecessary annotations and constraints to simplify the code (check CartItem for why)
    @Id
    @GeneratedValue(strategy = GenerationType.UUID) //instead of identity we set to uuid
    @Column(name = "id")
    private UUID id;
    //this field is also generated by the db we cannot apply generatedValue because it's only used for primary fields (@Id)
    @Column(name = "date_created", insertable = false, updatable = false) //tell hibernate to ignore this field when generating SQL statements
    private LocalDate dateCreated;

    @OneToMany(mappedBy = "cart")
    private Set<CartItem> cartItems = new LinkedHashSet<>();
}