server:
  port: 8090

spring:
  application:
    name: store
  datasource:
    url: jdbc:postgresql://localhost:5432/store #?createDatabaseIfNotExist=true   #this only works for mysql
    username: postgres
    password: Yp040721
#used to generate database tables using hibernate using a model first approach (not advised)
#to create the initial migration after db, rmb migrations, new, flyway init migration
  #jpa:
    #hibernate:
      #ddl-auto: create
  jpa:
    show-sql: true #display the sql statements sent to db in the console window

