spring:
  application:
    name: store
  datasource:
    url: jdbc:postgresql://localhost:5432/store #?createDatabaseIfNotExist=true   #this only works for mysql
    username: postgres
    password: Yp040721
server:
  port: 8090
